import { ICustomMetadataField } from "./metadataField";

export interface IPluginConfig {
  metadataFileName: string;
  // Link to the custom schema for this metadata object (generated by this plugin)
  metadataSchema?: string;
  fields: ICustomMetadataField[];
}